
-----Saurabh Pardeshi--------

-- Switch to SYSADMIN role---
USE ROLE SYSADMIN;

-- Create the import_warehouse 
CREATE OR REPLACE WAREHOUSE IMPORT_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300 -- 5 minutes in seconds
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create the transform_wh 
CREATE OR REPLACE WAREHOUSE TRANSFORM_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM',
    AUTO_SUSPEND = 300, -- 5 minutes in seconds
    AUTO_RESUME = TRUE,
    INITIALLY_SUSPENDED = TRUE;

-- Create the reporting_wh
CREATE OR REPLACE WAREHOUSE REPORTING_WH
WITH
    WAREHOUSE_SIZE = 'SMALL',
    MAX_CLUSTER_COUNT = 5, 
    AUTO_SUSPEND = 900, -- 15 minutes in seconds
    AUTO_RESUME = TRUE,
    INITIALLY_SUSPENDED = TRUE,
    SCALING_POLICY = 'ECONOMY';  

-- Create the STAGING database 
CREATE OR REPLACE DATABASE STAGING;

-- Create the PROD database 
CREATE OR REPLACE DATABASE PROD;



-- Create the RAW schema under STAGING database with default data retention of 3 days
CREATE OR REPLACE SCHEMA STAGING.RAW;
ALTER SCHEMA STAGING.RAW 
SET  DATA_RETENTION_TIME_IN_DAYS=3;

--Create external stage object
CREATE OR REPLACE STAGE STAGING.RAW.SOURCE
URL = 's3://snowflake-folder/parquet/';

-- Create the CLEAN schema under STAGING database with default data retention of 3 days
CREATE OR REPLACE SCHEMA STAGING.CLEAN;
ALTER SCHEMA STAGING.CLEAN 
SET  DATA_RETENTION_TIME_IN_DAYS=3;

-- Create the REPORTING schema under PROD database with default data retention of 90 days
CREATE OR REPLACE SCHEMA PROD.REPORTING;
ALTER SCHEMA PROD.REPORTING 
SET  DATA_RETENTION_TIME_IN_DAYS=90;


---CREATE RRESOURCE MONITOR ---
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE RESOURCE MONITOR IMPORT_WH_RM WITH CREDIT_QUOTA=100;
CREATE OR REPLACE RESOURCE MONITOR TRANSFORM_WH_RM WITH CREDIT_QUOTA=100;
CREATE OR REPLACE RESOURCE MONITOR REPORT_WH_RM WITH CREDIT_QUOTA=100;

ALTER WAREHOUSE IMPORT_WH SET RESOURCE_MONITOR = IMPORT_WH_RM;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = TRANSFORM_WH_RM;
ALTER WAREHOUSE REPORTING_WH SET RESOURCE_MONITOR = REPORT_WH_RM;

-----SWITCH TO SECURITYADMIN----
USE ROLE SECURITYADMIN;

------- CREATE OBJECT BASED ROLE AND GRANT PRIVILEGES -------

----WAREHOUSE USAGE ROLE-----
CREATE OR REPLACE ROLE IMPORT_WH_USAGE;
GRANT USAGE ON WAREHOUSE IMPORT_WH TO IMPORT_WH_USAGE;

CREATE OR REPLACE ROLE TRANSFORM_WH_USAGE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO TRANSFORM_WH_USAGE;

CREATE OR REPLACE ROLE REPORTING_WH_USAGE;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO REPORTING_WH_USAGE;

----STAGE USAGE ROLE-----
CREATE OR REPLACE ROLE STAGING_SOURCE_USER;
GRANT USAGE ON STAGE STAGING.RAW.SOURCE TO ROLE STAGING_SOURCE_USER;


----DATABASE AND SCHEMA USAGE ROLE-----
CREATE OR REPLACE ROLE STAGING_RAW_READONLY;
GRANT USAGE ON DATABASE STAGING TO ROLE STAGING_RAW_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING.RAW TO ROLE STAGING_RAW_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING.RAW TO ROLE STAGING_RAW_READONLY;

CREATE OR REPLACE ROLE STAGING_RAW_ALL;
GRANT ALL ON SCHEMA STAGING.RAW TO ROLE STAGING_RAW_ALL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING.RAW TO ROLE STAGING_RAW_ALL;

CREATE OR REPLACE ROLE STAGING_CLEAN_READONLY;
GRANT USAGE ON DATABASE STAGING TO ROLE STAGING_CLEAN_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING.CLEAN TO ROLE STAGING_CLEAN_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING.CLEAN TO ROLE STAGING_CLEAN_READONLY;

CREATE OR REPLACE ROLE STAGING_CLEAN_ALL;
GRANT ALL ON SCHEMA STAGING.CLEAN TO ROLE STAGING_CLEAN_ALL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING.CLEAN TO ROLE STAGING_CLEAN_ALL;

CREATE OR REPLACE ROLE PROD_REPORTING_READONLY;
GRANT USAGE ON DATABASE PROD TO ROLE PROD_REPORTING_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.REPORTING TO ROLE PROD_REPORTING_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD.REPORTING TO ROLE PROD_REPORTING_READONLY;

CREATE OR REPLACE ROLE PROD_REPORTING_ALL;
GRANT ALL ON SCHEMA PROD.REPORTING TO ROLE PROD_REPORTING_ALL;

---CREATE FUNCTIONAL BASED ROLE---

USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE IMPORT_ROLE;
GRANT MONITOR ON RESOURCE MONITOR IMPORT_WH_RM TO ROLE IMPORT_ROLE;
GRANT ROLE IMPORT_WH_USAGE TO ROLE IMPORT_ROLE;
GRANT ROLE STAGING_SOURCE_USER TO ROLE IMPORT_ROLE;
GRANT ROLE STAGING_RAW_READONLY TO ROLE IMPORT_ROLE;
GRANT ROLE STAGING_RAW_ALL TO ROLE IMPORT_ROLE;
GRANT ROLE STAGING_CLEAN_READONLY TO ROLE IMPORT_ROLE;
GRANT ROLE STAGING_CLEAN_ALL TO ROLE IMPORT_ROLE;

CREATE OR REPLACE ROLE TRANSFORM_ROLE;
GRANT MONITOR ON RESOURCE MONITOR TRANSFORM_WH_RM TO ROLE TRANSFORM_ROLE;
GRANT ROLE TRANSFORM_WH_USAGE TO ROLE TRANSFORM_ROLE;
GRANT ROLE STAGING_CLEAN_READONLY TO ROLE TRANSFORM_ROLE;
GRANT ROLE STAGING_CLEAN_ALL TO ROLE TRANSFORM_ROLE;
GRANT ROLE PROD_REPORTING_READONLY TO ROLE TRANSFORM_ROLE;
GRANT ROLE PROD_REPORTING_ALL TO ROLE TRANSFORM_ROLE;

CREATE OR REPLACE ROLE REPORT_ROLE;
GRANT MONITOR ON RESOURCE MONITOR REPORT_WH_RM TO ROLE REPORT_ROLE;
GRANT ROLE REPORTING_WH_USAGE TO ROLE REPORT_ROLE;
GRANT ROLE PROD_REPORTING_READONLY TO ROLE REPORT_ROLE;


-- CREATE USERS AND ASSIGN ROLE---
CREATE OR REPLACE USER IMPORT_USER PASSWORD = '12345ae'  DEFAULT_ROLE = IMPORT_ROLE;
GRANT ROLE IMPORT_ROLE TO USER IMPORT_USER;

CREATE OR REPLACE USER TRANSFORM_USER PASSWORD = '12345ae'   DEFAULT_ROLE = TRANSFORM_ROLE;
GRANT ROLE TRANSFORM_ROLE TO USER TRANSFORM_USER;

CREATE OR REPLACE USER REPORT_USER PASSWORD = '12345ae'   DEFAULT_ROLE = REPORT_ROLE;
GRANT ROLE REPORT_ROLE TO USER REPORT_USER; 




    

