---create udf
create or replace function trans_func(amount number)
returns string
language sql 
as
$$
select case when amount > 500 then 'High'
        when amount between 100 and 200 then 'Medium'
        else 'Low' end
$$
;
 
grant USAGE on FUNCTION trans_func(NUMBER) to role PC_DBT_ROLE;


CREATE MASKING POLICY GLOBALBANK.RAW_DATA.EMAIL_MASK AS
(EMAIL VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE = 'ADMIN' THEN EMAIL
ELSE REGEXP_REPLACE(EMAIL, '.+\@', '*****@')
END;
 
ALTER TABLE GLOBALBANK.RAW_DATA.CUSTOMER_RAW MODIFY COLUMN email SET MASKING POLICY GLOBALBANK.RAW_DATA.EMAIL_MASK;
 
CREATE MASKING POLICY GLOBALBANK.RAW_DATA.Phone_MASK AS
(PHONE VARCHAR) RETURNS VARCHAR ->
CASE WHEN CURRENT_ROLE = 'ADMIN' THEN PHONE
ELSE SUBSTR(PHONE, 0, 5) || '***-****'
END;
 
ALTER TABLE GLOBALBANK.RAW_DATA.CUSTOMER_RAW MODIFY COLUMN phone_number SET MASKING POLICY GLOBALBANK.RAW_DATA.Phone_MASK;
 
CREATE OR REPLACE MASKING POLICY GLOBALBANK.RAW_DATA.customer_id_MASK AS
(Cust_id VARCHAR) RETURNS VARCHAR ->
CASE
WHEN CURRENT_ROLE() = 'ADMIN' THEN Cust_id
ELSE 'XXXXXX'
END;
 
ALTER TABLE GLOBALBANK.RAW_DATA.CUSTOMER_RAW MODIFY COLUMN phone_number SET MASKING POLICY GLOBALBANK.RAW_DATA.customer_id_MASK;
 